
const CARDS={apple:{name:'青蘋序曲',edition:'Overture',img:'assets/card01.png',description:'序幕揭開，清爽、明亮的前奏，讓人期待今晚的首度相遇。'},mist:{name:'初霧歌行',edition:'Ballad',img:'assets/card02.png',description:'像茶香與歌聲交織，輕柔、悠長，讓每次的相遇都有了回音。'},plum:{name:'梅韻晚吟',edition:'Finale',img:'assets/card03.png',description:'像夜空中盛放的煙火，在熱烈掌聲中閃耀；在光芒漸歇時低鳴。'}};
const QUESTIONS=[
{q:'今晚，你想讓哪種風味\n成為你的第一杯？',affectsResult:true,options:[{text:'經典麥香配上清甜蘋果',score:{apple:3,mist:0}},{text:'輕盈茶湯配上甜蜜花香',score:{apple:0,mist:3}},{text:'刺激氣泡搭配酸甜醋飲',score:{apple:2,mist:1}}]},
{q:'你期待這款飲品的口感如何？',affectsResult:true,options:[{text:'細膩有層次、刺激氣泡感',score:{apple:3,mist:0}},{text:'茶韻悠長，慢慢回甘',score:{apple:0,mist:3}},{text:'酸甜青檸，輕盈延續',score:{apple:1,mist:2}}]},
{q:'如果這杯酒是一首歌，\n那這首歌的什麼部分會打動你？',archiveKey:'song',options:[{text:'前奏剛下就浮現記憶的經典排行'},{text:'副歌旋律無懈、朗朗上口流行金曲'},{text:'歌詞直擊人心、主歌餘音繞樑的不敗神作'}]},
{q:'在今晚的相遇中，\n你期待能為哪些時刻舉杯？',archiveKey:'toast',options:[{text:'與新的邂逅相遇時'},{text:'感受到餐點驚人美味而痛哭流涕的那刻'},{text:'聽到熟悉的旋律、準備忘我嘶吼的那刻'}]},
{q:'今晚，你想喝酒嗎？如果不喝，我將無條件推薦你適合的飲品！',alcoholQuestion:true,options:[{text:'想，我今天要喝到爛醉',alcohol:true},{text:'想，今晚來點微醺',alcohol:true},{text:'今天想喝無酒精',alcohol:false}]}
];
const DEFAULT_INVENTORY={apple:{planned:17,issued:0},mist:{planned:17,issued:0},plum:{planned:17,issued:0}};const STORAGE_KEY='rasaArchiveInventoryV3';const $=id=>document.getElementById(id);const screens=['homeScreen','quizScreen','drawScreen','resultScreen'];let step=0,scores={apple:0,mist:0},archiveAnswers={song:'',toast:''},alcoholChoice=null,ranking=['apple','mist'];
function show(id){screens.forEach(s=>$(s).classList.toggle('active',s===id))}function cloneDefault(){return JSON.parse(JSON.stringify(DEFAULT_INVENTORY))}function getInventory(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)),inv=cloneDefault();Object.keys(inv).forEach(k=>{if(saved&&saved[k]){inv[k].planned=Math.max(0,Number(saved[k].planned??17));inv[k].issued=Math.min(inv[k].planned,Math.max(0,Number(saved[k].issued??0)))}});return inv}catch(e){return cloneDefault()}}function setInventory(inv){localStorage.setItem(STORAGE_KEY,JSON.stringify(inv));renderInventory()}function remainingOf(i){return Math.max(0,i.planned-i.issued)}
function resetFlow(){step=0;scores={apple:0,mist:0};archiveAnswers={song:'',toast:''};alcoholChoice=null;ranking=['apple','mist'];$('cardField').classList.remove('shuffle');$('revealCard').classList.remove('flipped');show('homeScreen')}function startQuiz(){step=0;scores={apple:0,mist:0};archiveAnswers={song:'',toast:''};alcoholChoice=null;renderQuestion();show('quizScreen')}function renderQuestion(){const q=QUESTIONS[step],buttons=[$('choiceA'),$('choiceB'),$('choiceC')];$('progress').textContent=`${String(step+1).padStart(2,'0')} / 05`;$('questionText').textContent=q.q;buttons.forEach((b,i)=>{const o=q.options[i];b.hidden=!o;b.textContent=o?o.text:''})}
function answerQuestion(i){const q=QUESTIONS[step],o=q.options[i];if(!o)return;if(q.affectsResult&&o.score){scores.apple+=o.score.apple||0;scores.mist+=o.score.mist||0}if(q.archiveKey)archiveAnswers[q.archiveKey]=o.text;if(q.alcoholQuestion)alcoholChoice=o.alcohol;step++;if(step<QUESTIONS.length){renderQuestion();return}ranking=['apple','mist'].sort((a,b)=>{const diff=scores[b]-scores[a];if(diff!==0)return diff;const inv=getInventory();return inv[a].issued-inv[b].issued});showDraw()}
function showDraw(){show('drawScreen');setTimeout(()=>$('cardField').classList.add('shuffle'),420)}function chooseCard(){const inv=getInventory();if(alcoholChoice===false){if(remainingOf(inv.plum)>0){inv.plum.issued++;setInventory(inv)}return'plum'}const available=ranking.filter(k=>remainingOf(inv[k])>0);const chosen=available[0]||ranking[0];if(available[0]){inv[chosen].issued++;setInventory(inv)}return chosen}function reveal(){const key=chooseCard(),c=CARDS[key];$('resultImage').src=c.img;$('resultName').textContent=c.name;$('resultEdition').textContent=c.edition;$('resultDescription').textContent=c.description;$('songAnswer').textContent=archiveAnswers.song||'今晚的旋律';$('toastAnswer').textContent=archiveAnswers.toast||'值得記住的夜晚';$('revealCard').classList.remove('flipped');show('resultScreen');setTimeout(()=>$('revealCard').classList.add('flipped'),220)}
const LABELS={apple:['青蘋序曲','Overture'],mist:['初霧歌行','Ballad'],plum:['梅韻晚吟','Finale']};function renderInventory(){const inv=getInventory();$('stockTable').innerHTML=Object.keys(LABELS).map(k=>{const i=inv[k],[n,e]=LABELS[k];return`<article class="stock-row"><div class="stock-name"><strong>${n}</strong><small>${e}</small></div><div class="stock-metric"><span>已發放</span><strong>${i.issued}</strong></div><div class="stock-metric"><span>預備總數</span><strong>${i.planned}</strong></div><div class="stock-metric"><span>庫存</span><strong>${remainingOf(i)}</strong></div><div class="stock-controls"><button type="button" data-action="decrease" data-key="${k}">−</button><button type="button" data-action="increase" data-key="${k}">＋</button></div></article>`}).join('');$('issuedTotal').textContent=Object.values(inv).reduce((t,i)=>t+i.issued,0);$('plannedTotal').textContent=Object.values(inv).reduce((t,i)=>t+i.planned,0);$('remainingTotal').textContent=Object.values(inv).reduce((t,i)=>t+remainingOf(i),0)}function adjustIssued(k,d){const inv=getInventory();inv[k].issued=Math.min(inv[k].planned,Math.max(0,inv[k].issued+d));setInventory(inv)}$('stockTable').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;adjustIssued(b.dataset.key,b.dataset.action==='increase'?1:-1)});
$('homeStart').addEventListener('click',startQuiz);$('choiceA').addEventListener('click',()=>answerQuestion(0));$('choiceB').addEventListener('click',()=>answerQuestion(1));$('choiceC').addEventListener('click',()=>answerQuestion(2));$('drawButton').addEventListener('click',reveal);$('againButton').addEventListener('click',resetFlow);$('resetStock').addEventListener('click',()=>{if(confirm('確定重設為每款 17 杯、已發放 0 杯嗎？'))setInventory(cloneDefault())});function closeInv(){$('inventoryDialog').close()}$('closeInventory').addEventListener('click',closeInv);$('closeInventoryBottom').addEventListener('click',closeInv);$('inventoryDialog').addEventListener('click',e=>{if(e.target===$('inventoryDialog'))closeInv()});
let holdTimer=null,holdStart=0,holdFrame=null;function interactive(t){return!!t.closest('button,a,dialog,.choice,.reveal-card,img')}function stopHold(){clearTimeout(holdTimer);holdTimer=null;cancelAnimationFrame(holdFrame);holdFrame=null;$('holdFeedback').classList.remove('visible');$('holdFeedback').style.setProperty('--hold-progress','0%')}function progress(){const p=Math.min(100,(performance.now()-holdStart)/2000*100);$('holdFeedback').style.setProperty('--hold-progress',`${p}%`);if(p<100)holdFrame=requestAnimationFrame(progress)}$('app').addEventListener('pointerdown',e=>{if(interactive(e.target)||$('inventoryDialog').open)return;holdStart=performance.now();$('holdFeedback').classList.add('visible');progress();holdTimer=setTimeout(()=>{stopHold();renderInventory();$('inventoryDialog').showModal()},2000)});['pointerup','pointercancel','pointerleave'].forEach(t=>$('app').addEventListener(t,stopHold));renderInventory();
